<template><div><h1 id="functional-requirements-document" tabindex="-1"><a class="header-anchor" href="#functional-requirements-document"><span>Functional Requirements Document</span></a></h1>
<h2 id="_1-general-project-information" tabindex="-1"><a class="header-anchor" href="#_1-general-project-information"><span>1. General Project Information</span></a></h2>
<table>
<thead>
<tr>
<th>Project Name</th>
<th>Interface Design in the Middleware for PBCU Applications Integration</th>
</tr>
</thead>
<tbody>
<tr>
<td>Sprint</td>
<td>Sprint # 4</td>
</tr>
<tr>
<td>Assigned Team</td>
<td>Team J</td>
</tr>
<tr>
<td>Sprint Start Date</td>
<td>1 November of 2024</td>
</tr>
<tr>
<td>Delivery Date</td>
<td>15 November of 2024</td>
</tr>
</tbody>
</table>
<h2 id="_2-objective" tabindex="-1"><a class="header-anchor" href="#_2-objective"><span>2. Objective</span></a></h2>
<p>Integrate the Middleware with the Scanner system and the TOS (OTM) system to manage the vehicle scan confirmation, allowing the retrieval and sending of this information to release the container blockage.</p>
<h2 id="_3-sprint-scope" tabindex="-1"><a class="header-anchor" href="#_3-sprint-scope"><span>3. Sprint Scope</span></a></h2>
<p>The scope of the Sprint includes the integration of the Middleware with the Scanner system and the TOS (OTM). This integration will allow the capture of vehicle scan information, extract the license plate from the XML file, and send the confirmation to TOS for the release of associated blockages. The scope does not include modifications to the Scanner hardware or the TOS system, focusing solely on the integration and management of captured information.</p>
<h2 id="_4-functional-requirements" tabindex="-1"><a class="header-anchor" href="#_4-functional-requirements"><span>4. Functional Requirements</span></a></h2>
<h3 id="_4-1-general-description" tabindex="-1"><a class="header-anchor" href="#_4-1-general-description"><span>4.1 General Description</span></a></h3>
<ul>
<li><strong>RF-01:</strong> The Middleware must obtain the vehicle passage confirmation from the Scanner system by retrieving the XML file from an FTP server.</li>
<li><strong>RF-02:</strong> The Middleware must extract the license plate from the XML file (field <code v-pre>licensePlate</code>).</li>
<li><strong>RF-03:</strong> The Middleware must validate that the received information is complete before continuing with the processing.</li>
<li><strong>RF-04:</strong> The Middleware must handle connection or processing errors of the XML file and report these failures to the source system.</li>
<li><strong>RF-05:</strong> The Middleware must send the scan confirmation to the TOS (OTM) system for the release of the container blockage.</li>
<li><strong>RF-06:</strong> The Middleware must validate that the data sent to TOS is complete and error-free.</li>
<li><strong>RF-07:</strong> The Middleware must manage sending errors and retry in case of failures, reporting unresolved errors.</li>
</ul>
<h3 id="_4-2-use-cases" tabindex="-1"><a class="header-anchor" href="#_4-2-use-cases"><span>4.2 Use Cases</span></a></h3>
<h4 id="use-case-1-reception-and-processing-of-scanner-confirmation" tabindex="-1"><a class="header-anchor" href="#use-case-1-reception-and-processing-of-scanner-confirmation"><span>Use Case 1: Reception and Processing of Scanner Confirmation</span></a></h4>
<ul>
<li><strong>Actor:</strong> Middleware, Scanner (LPR Camera)</li>
<li><strong>Preconditions:</strong> The Scanner is operational and generating XML files with vehicle information.</li>
<li><strong>Main Flow:</strong>
<ol>
<li>The Middleware retrieves the XML file generated by the Scanner from the FTP server.</li>
<li>The Middleware extracts the license plate (<code v-pre>licensePlate</code>) and validates that the information is complete.</li>
<li>The Middleware temporarily stores the scan confirmation.</li>
</ol>
</li>
<li><strong>Postconditions:</strong> The license plate information is correctly stored and ready for transmission to the TOS.</li>
</ul>
<h4 id="use-case-2-sending-scan-confirmation-to-tos" tabindex="-1"><a class="header-anchor" href="#use-case-2-sending-scan-confirmation-to-tos"><span>Use Case 2: Sending Scan Confirmation to TOS</span></a></h4>
<ul>
<li><strong>Actor:</strong> Middleware, TOS (OTM)</li>
<li><strong>Preconditions:</strong> The Middleware has received and validated the scan information.</li>
<li><strong>Main Flow:</strong>
<ol>
<li>The Middleware sends the scan confirmation (license plate and other details) to the TOS system.</li>
</ol>
</li>
<li><strong>Postconditions:</strong> The TOS receives and processes the information to release the container blockage.</li>
</ul>
<h4 id="use-case-3-handling-communication-errors" tabindex="-1"><a class="header-anchor" href="#use-case-3-handling-communication-errors"><span>Use Case 3: Handling Communication Errors</span></a></h4>
<ul>
<li><strong>Actor:</strong> Middleware, TOS (OTM)</li>
<li><strong>Preconditions:</strong> The Middleware attempts to send the scan information to the TOS.</li>
<li><strong>Main Flow:</strong>
<ol>
<li>The Middleware detects an error when sending the data to the TOS.</li>
<li>The Middleware retries the operation a configurable number of times.</li>
<li>If the error persists, the Middleware reports the failure to the source system.</li>
</ol>
</li>
<li><strong>Postconditions:</strong> Errors are handled and reported correctly for review.</li>
</ul>
<h2 id="_5-validations-requested-by-the-client" tabindex="-1"><a class="header-anchor" href="#_5-validations-requested-by-the-client"><span>5. Validations Requested by the Client</span></a></h2>
<h4 id="v-01-vehicle-license-plate-validation" tabindex="-1"><a class="header-anchor" href="#v-01-vehicle-license-plate-validation"><span>V-01: Vehicle License Plate Validation</span></a></h4>
<ul>
<li><strong>Description:</strong> The Middleware must validate that the license plate captured from the XML file follows the correct format.</li>
<li><strong>Acceptance Criteria:</strong>
<ul>
<li>The license plate must consist of 6 alphanumeric characters, following the format defined by current legislation (e.g., 3 letters followed by 3 numbers).</li>
<li>The Middleware must reject any license plate that does not comply with this format.</li>
</ul>
</li>
</ul>
<h4 id="v-02-complete-xml-file-validation" tabindex="-1"><a class="header-anchor" href="#v-02-complete-xml-file-validation"><span>V-02: Complete XML File Validation</span></a></h4>
<ul>
<li><strong>Description:</strong> The Middleware must verify that the XML file received from the Scanner system contains all the necessary information to be processed correctly.</li>
<li><strong>Acceptance Criteria:</strong>
<ul>
<li>The file must contain the <code v-pre>licensePlate</code> field with the vehicle's plate number.</li>
<li>The file must include required information, such as the date and time of the scan.</li>
<li>The Middleware must reject any XML file that does not comply with the expected structure.</li>
</ul>
</li>
</ul>
<h4 id="v-03-data-completeness-validation-for-sending-to-tos" tabindex="-1"><a class="header-anchor" href="#v-03-data-completeness-validation-for-sending-to-tos"><span>V-03: Data Completeness Validation for Sending to TOS</span></a></h4>
<ul>
<li><strong>Description:</strong> The Middleware must verify that all the necessary data for sending to the TOS (OTM) system is complete and correct.</li>
<li><strong>Acceptance Criteria:</strong>
<ul>
<li>Data such as the vehicle license plate, container details, and the date must be present in the message.</li>
<li>If any of this data is missing, the Middleware will not send the confirmation to the TOS and will generate an error message.</li>
</ul>
</li>
</ul>
<h4 id="v-04-ftp-server-connection-validation" tabindex="-1"><a class="header-anchor" href="#v-04-ftp-server-connection-validation"><span>V-04: FTP Server Connection Validation</span></a></h4>
<ul>
<li><strong>Description:</strong> The Middleware must verify that the connection to the Scanner's FTP server is active before attempting to download the XML file.</li>
<li><strong>Acceptance Criteria:</strong>
<ul>
<li>The Middleware must attempt to establish a connection to the FTP server.</li>
<li>If the connection cannot be established, the Middleware must generate an error and notify the source system.</li>
</ul>
</li>
</ul>
<h4 id="v-05-tos-response-validation" tabindex="-1"><a class="header-anchor" href="#v-05-tos-response-validation"><span>V-05: TOS Response Validation</span></a></h4>
<ul>
<li><strong>Description:</strong> The Middleware must validate the response from the TOS system to ensure that the container's lock has been correctly released.</li>
<li><strong>Acceptance Criteria:</strong>
<ul>
<li>The TOS must confirm that it has received and processed the scan confirmation correctly.</li>
<li>In case of an error, the Middleware must log the error and retry the process based on the configuration.</li>
</ul>
</li>
</ul>
<h4 id="v-06-error-handling-in-the-sending-process" tabindex="-1"><a class="header-anchor" href="#v-06-error-handling-in-the-sending-process"><span>V-06: Error Handling in the Sending Process</span></a></h4>
<ul>
<li><strong>Description:</strong> The Middleware must handle errors in sending data to the TOS, retrying the sending process if necessary.</li>
<li><strong>Acceptance Criteria:</strong>
<ul>
<li>If the confirmation sending fails, the Middleware must attempt to resend it up to a configurable maximum number of retries.</li>
<li>If the resend attempts fail after the defined number of retries, an error should be reported and logged.</li>
</ul>
</li>
</ul>
<h4 id="v-07-validation-of-data-format-when-sending-to-the-tos" tabindex="-1"><a class="header-anchor" href="#v-07-validation-of-data-format-when-sending-to-the-tos"><span>V-07: Validation of Data Format when Sending to the TOS</span></a></h4>
<ul>
<li><strong>Description:</strong> The Middleware must verify that the data sent to the TOS follows the required format.</li>
<li><strong>Acceptance Criteria:</strong>
<ul>
<li>The data must be sent in the required XML/JSON format or the format specified by the TOS system.</li>
<li>If the data does not follow the required format, the Middleware must generate an error and not send the data to the TOS.</li>
</ul>
</li>
</ul>
<h2 id="_6-assumptions-and-dependencies" tabindex="-1"><a class="header-anchor" href="#_6-assumptions-and-dependencies"><span>6. Assumptions and Dependencies</span></a></h2>
<ul>
<li>The FTP server of the Scanner is available and correctly configured for file access and transfer.</li>
<li>The TOS service is operational and prepared to receive scanning information.</li>
<li>The test environment for the TOS and Scanner systems must be configured and accessible for integration testing.</li>
<li>Access to the documentation of the Scanner system and TOS (OTM) to verify connection details and format requirements.</li>
</ul>
<h2 id="_7-sequence" tabindex="-1"><a class="header-anchor" href="#_7-sequence"><span>7. Sequence</span></a></h2>
<h3 id="" tabindex="-1"><a class="header-anchor" href="#"><span><img src="@source/assets/Scanner/secuencia_para_scanner_720.png" alt=""></span></a></h3>
<h2 id="_8-service-data" tabindex="-1"><a class="header-anchor" href="#_8-service-data"><span>8. Service Data</span></a></h2>
<div class="language-json line-numbers-mode" data-highlighter="prismjs" data-ext="json" data-title="json"><pre v-pre><code><span class="line">Request</span>
<span class="line"><span class="token punctuation">{</span></span>
<span class="line">   <span class="token property">"containerNumber"</span><span class="token operator">:</span> <span class="token string">"MMAU1234567"</span><span class="token punctuation">,</span></span>
<span class="line">   <span class="token property">"truckPlate"</span><span class="token operator">:</span> <span class="token string">"UYT987"</span><span class="token punctuation">,</span></span>
<span class="line">   <span class="token property">"dateTimeScan"</span><span class="token operator">:</span> <span class="token string">"2024-07-21 21:45:22"</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-json line-numbers-mode" data-highlighter="prismjs" data-ext="json" data-title="json"><pre v-pre><code><span class="line">Response</span>
<span class="line"><span class="token punctuation">{</span></span>
<span class="line">   <span class="token property">"statusResponse"</span><span class="token operator">:</span> <span class="token string">"Ok"</span><span class="token punctuation">,</span></span>
<span class="line">   <span class="token property">"code"</span><span class="token operator">:</span> <span class="token number">200</span><span class="token punctuation">,</span></span>
<span class="line">   <span class="token property">"description"</span><span class="token operator">:</span> <span class="token string">"sucessfull"</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_9-unit-tests" tabindex="-1"><a class="header-anchor" href="#_9-unit-tests"><span>9. Unit Tests</span></a></h2>
<h3 id="_9-1-test-environment-configuration" tabindex="-1"><a class="header-anchor" href="#_9-1-test-environment-configuration"><span>9.1 Test Environment Configuration</span></a></h3>
<h3 id="-1" tabindex="-1"><a class="header-anchor" href="#-1"><span><img src="@source/assets/Scanner/Configuracion del entorno de pruebas.PNG" alt=""></span></a></h3>
<h3 id="_9-2-service-and-mock-initialization" tabindex="-1"><a class="header-anchor" href="#_9-2-service-and-mock-initialization"><span>9.2 Service and Mock Initialization</span></a></h3>
<h3 id="-2" tabindex="-1"><a class="header-anchor" href="#-2"><span><img src="@source/assets/Scanner/inicializacion del servicio.PNG" alt=""></span></a></h3>
<h3 id="_9-3-processallfiles-tests" tabindex="-1"><a class="header-anchor" href="#_9-3-processallfiles-tests"><span>9.3 processAllFiles Tests</span></a></h3>
<h4 id="_9-3-1-successfully-process-files" tabindex="-1"><a class="header-anchor" href="#_9-3-1-successfully-process-files"><span>9.3.1 Successfully Process Files</span></a></h4>
<h3 id="-3" tabindex="-1"><a class="header-anchor" href="#-3"><span><img src="@source/assets/Scanner/Procesar archivos correctamente1.png" alt=""></span></a></h3>
<h3 id="-4" tabindex="-1"><a class="header-anchor" href="#-4"><span><img src="@source/assets/Scanner/Procesar archivos correctamente2.png" alt=""></span></a></h3>
<h4 id="_9-3-2-missing-data-handling" tabindex="-1"><a class="header-anchor" href="#_9-3-2-missing-data-handling"><span>9.3.2 Missing Data Handling</span></a></h4>
<h3 id="-5" tabindex="-1"><a class="header-anchor" href="#-5"><span><img src="@source/assets/Scanner/menajo de datos faltantes.PNG" alt=""></span></a></h3>
<h4 id="_9-3-3-sftp-connection-error" tabindex="-1"><a class="header-anchor" href="#_9-3-3-sftp-connection-error"><span>9.3.3 SFTP Connection Error</span></a></h4>
<h3 id="-6" tabindex="-1"><a class="header-anchor" href="#-6"><span><img src="@source/assets/Scanner/Error de conexión SFTP.PNG" alt=""></span></a></h3>
<h4 id="_9-3-4-error-listing-files" tabindex="-1"><a class="header-anchor" href="#_9-3-4-error-listing-files"><span>9.3.4 Error Listing Files</span></a></h4>
<h3 id="-7" tabindex="-1"><a class="header-anchor" href="#-7"><span><img src="@source/assets/Scanner/Error al listar archivos.PNG" alt=""></span></a></h3>
<h3 id="_9-4-uploadfile-tests" tabindex="-1"><a class="header-anchor" href="#_9-4-uploadfile-tests"><span>9.4 uploadFile Tests</span></a></h3>
<h4 id="_9-4-1-successful-upload" tabindex="-1"><a class="header-anchor" href="#_9-4-1-successful-upload"><span>9.4.1 Successful Upload</span></a></h4>
<h3 id="-8" tabindex="-1"><a class="header-anchor" href="#-8"><span><img src="@source/assets/Scanner/Pruebas de uploadFile- Subida exitosa.PNG" alt=""></span></a></h3>
<h4 id="_9-4-2-file-already-exists" tabindex="-1"><a class="header-anchor" href="#_9-4-2-file-already-exists"><span>9.4.2 File Already Exists</span></a></h4>
<h3 id="-9" tabindex="-1"><a class="header-anchor" href="#-9"><span><img src="@source/assets/Scanner/Archivo existente.PNG" alt=""></span></a></h3>
<h4 id="_9-4-3-upload-error" tabindex="-1"><a class="header-anchor" href="#_9-4-3-upload-error"><span>9.4.3 Upload Error</span></a></h4>
<h3 id="-10" tabindex="-1"><a class="header-anchor" href="#-10"><span><img src="@source/assets/Scanner/Error al subir.PNG" alt=""></span></a></h3>
<h2 id="_10-annexes" tabindex="-1"><a class="header-anchor" href="#_10-annexes"><span>10. Annexes</span></a></h2>
<h4 id="request" tabindex="-1"><a class="header-anchor" href="#request"><span>Request</span></a></h4>
<table>
<thead>
<tr>
<th>No.</th>
<th>Field</th>
<th>Type</th>
<th>Size/Format</th>
<th>Domain</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>containerNumber</td>
<td>String</td>
<td>15/Varchar</td>
<td></td>
</tr>
<tr>
<td>2</td>
<td>truckPlate</td>
<td>String</td>
<td>10/Varchar</td>
<td></td>
</tr>
<tr>
<td>3</td>
<td>dateTimeScan</td>
<td>Datetime</td>
<td>yyyy-MM-dd HH:mm:ss</td>
<td></td>
</tr>
</tbody>
</table>
<h4 id="response" tabindex="-1"><a class="header-anchor" href="#response"><span>Response</span></a></h4>
<table>
<thead>
<tr>
<th>No.</th>
<th>Field</th>
<th>Type</th>
<th>Size/Format</th>
<th>Domain</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>statusResponse</td>
<td>String</td>
<td>5</td>
<td>True, false</td>
</tr>
<tr>
<td>2</td>
<td>code</td>
<td>Number</td>
<td>2</td>
<td></td>
</tr>
<tr>
<td>3</td>
<td>description</td>
<td>String</td>
<td>250</td>
<td></td>
</tr>
</tbody>
</table>
</div></template>



<style>
/* Justificar el texto en los encabezados */
h2, h3 {
    text-align: justify;
}

/* Justificar el texto en los párrafos */
p {
    text-align: justify;
}

img {
    display: block;
    margin: 0 auto;  /* Centra la imagen */
    width: 80%;  /* Ajusta el tamaño al 80% del contenedor */
    max-width: 600px;  /* Establece un ancho máximo para la imagen */
  }
  /* Estilo general para todas las tablas */
table {
    width: 100%;  /* Las tablas ocuparán todo el ancho del contenedor */
    border-collapse: collapse;  /* Colapsa los bordes para que no haya espacio entre celdas */
    table-layout: fixed;  /* Establece que todas las celdas tengan el mismo ancho */
}

/* Estilo para las celdas de la tabla */
th, td {
    padding: 8px;
    text-align: left;
    border: 1px solid #ddd;  /* Bordes suaves alrededor de cada celda */
    overflow: hidden;  /* Para evitar que el texto se desborde de las celdas */
    word-wrap: break-word;  /* Hace que el texto largo se ajuste a la celda */
}
th, td {
    width: 20%;  /* Ajusta este porcentaje según el número de columnas */
}

/* Estilo para las tablas en pantallas pequeñas */
@media (max-width: 768px) {
    table {
        display: block;  /* Convierte la tabla en un bloque deslizante */
        overflow-x: auto;  /* Permite que la tabla se deslice horizontalmente */
        white-space: nowrap;  /* Evita que el texto se ajuste */
    }
}
</style>